# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: check_acpype

on: [push]

jobs:
   build:
      runs-on: ${{ matrix.os }}
      strategy:
         matrix:
            os: [ubuntu-latest, macOS]
            python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

      steps:
         - uses: actions/checkout@v2

         - name: Set up Python ${{ matrix.python-version }}
           uses: actions/setup-python@v2
           with:
              python-version: ${{ matrix.python-version }}

         - name: Install OpenBabel Python Module and Hack it
           run: |
              if [ "$RUNNER_OS" == macOS ]; then
                 echo ">>>>>>SKIP macOS"
              elif [ "$RUNNER_OS" == "Linux" ]; then
                 sudo apt-get install --no-install-recommends -y python3-openbabel
                 echo ln -s /usr/lib/python3/dist-packages/openbabel $pythonLocation/lib/python${{ matrix.python-version }}/
              fi
